name: CustomUnlockCodes
version: 0.2
author: LadyProxima
main: me.ladyproxima.customunlockcodes.CustomUnlockCodes
api-version: 1.12.2
depend:
- Vault
commands:
  freischalten:
    usage: /freischalten <code>
    description: Schaltet den Spieler frei.
